FROM postgres

ENV POSTGRES_USER=rider
ENV POSTGRES_PASSWORD=rider
ENV POSTGRES_DB=rider

EXPOSE 5432

CMD ["postgres"]

#docker build -t name -f path/to/Dockerfile .
#docker run --name name -p 5433:5432 -d ddd