FROM postgres

ENV POSTGRES_USER=driver
ENV POSTGRES_PASSWORD=driver
ENV POSTGRES_DB=driver

EXPOSE 5432

CMD ["postgres"]

#docker build -t name -f path/to/Dockerfile .
#docker run --name name -p 5433:5432 -d ddd