spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: Rider
  datasource:
    url: jdbc:postgresql://localhost:5434/rider
    username: rider
    password: rider
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081