spring:
  application:
    name: Driver
  datasource:
    url: jdbc:postgresql://localhost:5434/rider
    username: rider
    password: rider
    driver-class-name: org.postgresql.Driver
server:
  port: 8081