spring:
  application:
    name: Driver
  datasource:
    url: jdbc:postgresql://localhost:5433/driver
    username: driver
    password: driver
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080